spring:
  datasource:
      url: jdbc:mysql://localhost:3306/crm_adm?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: assya
      password: assya
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  # Application configuration.
server:
  port: 8090

  # Logging configuration.
  logging:
    level:
      org.springframework.web: ERROR
      com.crm: DEBUG
      org.hibernate: ERROR
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"