spring:
  data:
# mongodb configuration.
    mongodb:
      host: localhost
      port: 27017
      database: crm_adm
# Application configuration.
  server:
    port: 8088

  # Logging configuration.
  logging:
    level:
      org.springframework.web: ERROR
      com.crm: DEBUG
      org.hibernate: ERROR
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"